#Allow use command to entry creative dimension.
allow_use_command = true
#Allow use bed to entry creative dimension.
allow_use_bed = false
#Allow use ponder on wrench to go creative dimension.
allow_wrench_ponder = false
#Items that are banned from using in creative dimension
items = ["mekanism:teleporter_frame", "mekanism:quantum_entangloporter"]

[grid_block]
	#Block placed in odd places.
	odd = "minecraft:light_blue_concrete"
	#Block placed in odd places.
	even = "minecraft:yellow_concrete"

